services:
  - type: web
    name: agentcare-service
    env: docker
    plan: free
    disk:
      name: agentcare-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SQLITE_DB_PATH
        value: /data/clinico.db
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: LOGFIRE_TOKEN
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
